name: hawk
description: This library provides in-app errors catching and sending them to the Hawk monitoring system. You can also send errors, which you caught in try-catch.
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  http: ^0.13.4
  stack_trace: ^1.10.0

dev_dependencies:
  test: ^1.16.0
